version: 2

sources:
  - name: core
    database: '{{ var("DBT_DATABASE") }}'
    schema: '{{ var("DBT_SCHEMA") }}'
    
    tables:
      - name: nyseInfo_ext
      - name: nasdaqInfo_ext


      
      
      