id: GCP_Infrastructure
namespace: null

tasks:

  #Create storage bucket in Google Cloud Storage based on values in KV Store
  - id: create_gcs_bucket
    type: io.kestra.plugin.gcp.gcs.CreateBucket
    ifExists: SKIP
    storageClass: REGIONAL
    name: "{{kv('GCP_BUCKET_NAME')}}"

  #Create dataset in BigQuery based on values in KV Store
  - id: create_bq_dataset
    type: io.kestra.plugin.gcp.bigquery.CreateDataset
    name: "{{kv('GCP_DATASET')}}"
    ifExists: SKIP

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"


#Trigger this flow on successful creation of KVs from Create_GCP_KVs flow
triggers:
  - id: trigger_on_Create_GCP_KVs_success
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: flow_trigger
      flows:
        - namespace: stockmarketanalysis
          flowId: Create_GCP_KVs
          states: [SUCCESS]