version: 2

sources:
  - name: staging
    database: rugged-shuttle-447818-h7
    schema: stockMarketAnalysis

    tables:
      - name: priceData_ext
      - name: reports_ext
      
      
      