version: 2

sources:
  - name: staging
    database: '{{ var("DBT_DATABASE") }}'
    schema: '{{ var("DBT_SCHEMA") }}'

    tables:
      - name: priceData_ext
      - name: reports_ext
      
      
      